const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Behaviors.Rotate,
		C3.Plugins.Button,
		C3.Plugins.progressbar,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.GameRecorder,
		C3.Plugins.Audio,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.StopAll
	];
};
self.C3_JsPropNameTable = [
	{Платформер: 0},
	{Твёрдый: 0},
	{СледитьЗа: 0},
	{Спрайт: 0},
	{Спрайт2: 0},
	{Якорь: 0},
	{ТайловыйФон: 0},
	{Поворот: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{ТайловыйФон2: 0},
	{Спрайт7: 0},
	{Спрайт8: 0},
	{Безымянный: 0},
	{Кнопка: 0},
	{Кнопка2: 0},
	{Кнопка3: 0},
	{Безымянкепаый: 0},
	{Кнопка4: 0},
	{Спрайт9: 0},
	{Индикатор: 0},
	{Перетаскивание: 0},
	{Спрайт10: 0},
	{Текст: 0},
	{Спрайт11: 0},
	{Кнопка5: 0},
	{ВводТекста: 0},
	{Текст2: 0},
	{Текст3: 0},
	{ЗаписьИгры: 0},
	{Спрайт12: 0},
	{Текст4: 0},
	{Аудио: 0},
	{Текст5: 0},
	{Спрайт13: 0},
	{Спрайт14: 0},
	{ТайловыйФон3: 0},
	{Спрайт15: 0},
	{Спрайт16: 0},
	{Текст6: 0},
	{Спрайт17: 0}
];

self.InstanceType = {
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Безымянный: class extends self.ISpriteInstance {},
	Кнопка: class extends self.IButtonInstance {},
	Кнопка2: class extends self.IButtonInstance {},
	Кнопка3: class extends self.IButtonInstance {},
	Безымянкепаый: class extends self.ISpriteInstance {},
	Кнопка4: class extends self.IButtonInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Индикатор: class extends self.IProgressBarInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Кнопка5: class extends self.IButtonInstance {},
	ВводТекста: class extends self.ITextInputInstance {},
	Текст2: class extends self.ITextInstance {},
	Текст3: class extends self.ITextInstance {},
	ЗаписьИгры: class extends self.IInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Текст4: class extends self.ITextInstance {},
	Аудио: class extends self.IInstance {},
	Текст5: class extends self.ITextInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	Спрайт14: class extends self.ISpriteInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	Спрайт15: class extends self.ISpriteInstance {},
	Спрайт16: class extends self.ISpriteInstance {},
	Текст6: class extends self.ITextInstance {},
	Спрайт17: class extends self.ISpriteInstance {}
}